export const CURRENT_TEAMS = [
  'Air France',
  'Amadeus 1',
  'Amadeus 2',
  'Ansys',
  'Arm 1',
  'Arm 2',
  'EkipEkip',
  'EureSPIKE',
  'EURESPIKE 2',
  'FortiTeam',
  'InDeMENTAble',
  'Instant System 1',
  'Instant System 2',
  'NXP 1',
  'NXP 2',
  'Renault',
  'Thales',
  'Thales CDI',
] as const;
